# Generated by Django 4.0.6 on 2022-07-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=10)),
                ('set_weight', models.CharField(max_length=10)),
                ('number_of_reps', models.IntegerField()),
            ],
        ),
    ]
